channels:
  - conda-forge

dependencies:
  # Mirrors requires-python in pyproject.toml
  - "python>=3.10.12,<3.11|>=3.11.4"
  - pytest
  - jupyterlab>=3.0.0,<4.0.0
  - nodejs
  - black
  - pytest-tornasync==0.6.0.post2
