# a mybinder.org-ready environment for demoing jupyter-archive
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupyter-archive-demo
#
name: jupyter-archive-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.8,<3.9.0a0
  - jupyterlab >=3,<4.0.0a0
  # labextension build dependencies
  - nodejs >=14,<15
  - pip
  - wheel
  # Fix binder
  - parso >=0.8.0,<0.9.0
  - jupyter_telemetry >=0.1.0
